### PR TITLE
Add support for Trace.interval

### PR DESCRIPTION
**Pull request by marcpareoee**
Updates API routes and models to add the optional `interval` field to Traces.

### CODE REVIEW

**Comment by marcpareoee** [comment]
That can done, sure

**Comment by matthewgee** [comment]
+1 on phils comment. fuel type should be a separate from frequency

**Comment by matthewgee** [comment]
One additional consideration: how are submetered traces going to be distinguished? The Lime/Nat Grid instance will include our first traces where there are multiple 1-minute electricity traces for a single building, right now there is not way of distinguishing a whole-building trace (one to one relationships between traces and projects) from a sub-metered trace (many-to-one relationships of fuel-type-specific traces to projects). This doesn't need to be an additional meta data field because it will presumably be handled implicitly with the foreign keys, but I think it would be helpful to be able to query this table explicitly for submetered traces.

**Comment by philngo** [comment]
That's a good question to discuss, but let's move the discussion so we can accept this PR.

**Pull request merged**
