### PR TITLE
Warehouse project summary mart for dashboard

### PR DESCRIPTION
**Pull request by philngo**
WIP

Project summary table will be the main backend for dashboards. It summarizes results by project, creating a table with one row per project and automatically pivoting and joining metadata.

It also filters out blacklisted project or trace IDs, a step which is required for filtering doubled traces which have different trace ids. The list of blacklisted traces will need to be created or populated separately.

TODO:
 - management command and API for editing list of blacklisted traces and projects.

### CODE REVIEW

**Comment by marcpareoee** [comment]
Wow, pretty cool to build the tables on the fly.

Thoughts on writing tests for each of the columns in the warehouse table? Looks like it's going to be a beast of a job, but pretty important, too.

**Comment by philngo** [comment]
Some tests will be easier than others, but we should be able to do some spot checking, starting with the tests that are implemented currently as a periscope view (like checking that there are no duplicate projects/traces).

I've been considering appending a basic test suite to the end of the create command, so that after each create/destroy cycle, the tests will automatically run then log and/or print a report. We might also consider computing and logging/printing some of the summary values that are displayed in the dashboard so that if we have an idea of what we expect them to be, we can compare them to each other.

**Comment by marcpare** [comment]
Oh, that idea of a post-creation audit is really good. That approach has had the most bang-for-the-buck in the similarly hard-to-test ETL pipeline.

**Comment by philngo** [comment]
@mcgeeyoung That's an interesting one. For now I'll change it to an app setting (environment variable) but if it changes quarterly we're going to need a better solution.

**Pull request merged**
